// Export address-indexed C pseudocode, instruction listing, symbols and call graph.
// @category NiZ
import ghidra.app.script.GhidraScript;
import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.app.decompiler.DecompileOptions;
import ghidra.program.model.listing.*;
import ghidra.program.model.symbol.*;
import ghidra.program.model.mem.MemoryBlock;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;

public class ExportRecovered extends GhidraScript {
    private PrintWriter writer(Path p) throws Exception {
        return new PrintWriter(Files.newBufferedWriter(p, StandardCharsets.UTF_8));
    }
    private String clean(String s) { return s.replace('\t', ' ').replace('\n', ' ').replace('\r', ' '); }
    public void run() throws Exception {
        Path output = Paths.get(getScriptArgs()[0]);
        Files.createDirectories(output.resolve("functions"));
        // Replace earlier exports, including obsolete names and rejected function fragments.
        try (var files = Files.list(output.resolve("functions"))) {
            for (Path old : files.filter(p -> p.getFileName().toString().matches("[0-9a-fA-F]{8}_.*\\.c")).toList())
                if (Files.readString(old).startsWith("/* Address: 0x")) Files.delete(old);
        }
        DecompInterface decompiler = new DecompInterface();
        DecompileOptions options = new DecompileOptions();
        options.grabFromProgram(currentProgram);
        options.setRespectReadOnly(true);
        decompiler.setOptions(options);
        decompiler.openProgram(currentProgram);
        int total = 0, succeeded = 0, failed = 0, instructions = 0;
        long codeBytes = 0, functionBytes = 0;
        try (PrintWriter c = writer(output.resolve("all_functions.c"));
             PrintWriter index = writer(output.resolve("functions.tsv"));
             PrintWriter calls = writer(output.resolve("callgraph.tsv"));
             PrintWriter failures = writer(output.resolve("decompile_failures.tsv"))) {
            c.println("/* Ghidra C pseudocode. Addresses and autogenerated types are retained. */");
            c.println("/* This is an analysis export, not a buildable replacement firmware. */\n");
            index.println("address\tname\tbody_bytes\tdecompiled\tsignature");
            calls.println("caller_address\tcaller\tcallee_address\tcallee");
            failures.println("address\tname\terror");
            for (Function f : currentProgram.getFunctionManager().getFunctions(true)) {
                if (monitor.isCancelled()) break;
                if (f.isExternal()) continue;
                total++;
                long size = f.getBody().getNumAddresses(); functionBytes += size;
                DecompileResults result = decompiler.decompileFunction(f, 60, monitor);
                boolean ok = result.decompileCompleted() && result.getDecompiledFunction() != null;
                String heading = "/* Address: 0x" + f.getEntryPoint() + "; body bytes: " + size + " */\n";
                String code;
                if (ok) { succeeded++; code = result.getDecompiledFunction().getC(); }
                else {
                    failed++; code = "/* Decompilation failed: " + clean(result.getErrorMessage()) + " */\n";
                    failures.println(f.getEntryPoint() + "\t" + clean(f.getName()) + "\t" + clean(result.getErrorMessage()));
                }
                c.println(heading + code);
                String filename = f.getEntryPoint() + "_" + f.getName().replaceAll("[^A-Za-z0-9_.-]", "_") + ".c";
                Files.writeString(output.resolve("functions").resolve(filename), heading + code, StandardCharsets.UTF_8);
                index.println(f.getEntryPoint() + "\t" + clean(f.getName()) + "\t" + size + "\t" + ok + "\t" + clean(f.getSignature().toString()));
                for (Function callee : f.getCalledFunctions(monitor))
                    calls.println(f.getEntryPoint() + "\t" + clean(f.getName()) + "\t" + callee.getEntryPoint() + "\t" + clean(callee.getName()));
            }
        } finally { decompiler.dispose(); }
        try (PrintWriter listing = writer(output.resolve("listing.asm"));
             PrintWriter xrefs = writer(output.resolve("references.tsv"))) {
            xrefs.println("from\tfunction\tto\ttype");
            for (Instruction ins : currentProgram.getListing().getInstructions(true)) {
                instructions++; codeBytes += ins.getLength();
                Function f = getFunctionContaining(ins.getAddress());
                byte[] bytes = ins.getBytes(); StringBuilder hex = new StringBuilder();
                for (byte b : bytes) hex.append(String.format("%02x", b & 255));
                listing.printf("%s  %-20s  %s%n", ins.getAddress(), hex.toString(), ins.toString());
                for (Reference ref : ins.getReferencesFrom())
                    xrefs.println(ins.getAddress() + "\t" + (f == null ? "" : clean(f.getName())) + "\t" + ref.getToAddress() + "\t" + ref.getReferenceType());
            }
        }
        try (PrintWriter symbols = writer(output.resolve("symbols.tsv"))) {
            symbols.println("address\ttype\tsource\tname");
            for (Symbol s : currentProgram.getSymbolTable().getAllSymbols(true))
                symbols.println(s.getAddress() + "\t" + s.getSymbolType() + "\t" + s.getSource() + "\t" + clean(s.getName(true)));
        }
        try (PrintWriter blocks = writer(output.resolve("memory_map.tsv"))) {
            blocks.println("name\tstart\tend\tbytes\tread\twrite\texecute\tinitialized");
            for (MemoryBlock b : currentProgram.getMemory().getBlocks())
                blocks.println(b.getName() + "\t" + b.getStart() + "\t" + b.getEnd() + "\t" + b.getSize() + "\t" + b.isRead() + "\t" + b.isWrite() + "\t" + b.isExecute() + "\t" + b.isInitialized());
        }
        try (PrintWriter summary = writer(output.resolve("summary.json"))) {
            summary.printf("{\n  \"functions\": %d,\n  \"decompiled\": %d,\n  \"failed\": %d,\n  \"instructions\": %d,\n  \"instruction_bytes\": %d,\n  \"function_body_bytes\": %d\n}\n",
                total, succeeded, failed, instructions, codeBytes, functionBytes);
        }
        println("Exported " + total + " functions; decompiled " + succeeded + "; failed " + failed + " to " + output);
    }
}
